---
title: "인터랙티브 문서"
format: 
  html:
    page-layout: custom
server: shiny
---

# 간헐천 데이터

미국 옐로스톤 국립공원 `Old Faithful Geyser` 에서 수집된 R 내장데이터셋.

```{r}
#| panel: sidebar
sliderInput("bins", "구간 갯수:", 
            min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r}
#| context: server

output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser 데이터
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```


# 붓꽃 


```{r}
#| panel: sidebar
vars <- setdiff(names(iris), "Species")
selectInput('xcol', 'X 변수', vars)
selectInput('ycol', 'Y 변수', vars, selected = vars[[2]])
numericInput('clusters', '군집 갯수', 3, min = 1, max = 9)
```

```{r}
#| panel: fill
plotOutput('cluster_plot')
```

```{r}
#| context: server
selectedData <- reactive({
    iris[, c(input$xcol, input$ycol)]
  })

clusters <- reactive({
  kmeans(selectedData(), input$clusters)
})

output$cluster_plot <- renderPlot({
  palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
    "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

  par(mar = c(5.1, 4.1, 0, 1))
  plot(selectedData(),
       col = clusters()$cluster,
       pch = 20, cex = 3)
  points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
})
```
